#!/bin/sh

cd openthread
echo Installing dependencies
script/bootstrap
echo Running OpenThread bootstrap
./bootstrap
echo Building NCP
make -f examples/Makefile-kw41z clean
make -f examples/Makefile-kw41z BORDER_AGENT=1 BORDER_ROUTER=1 COMMISSIONER=1 UDP_PROXY=1
cd build/kw41z/examples/apps/ncp
arm-none-eabi-objcopy -O ihex ot-ncp-ftd ot-ncp-ftd.hex
